site:
  title: Quarkiverse Documentation
  url: https://docs.quarkiverse.io
  start_page: index::index.adoc
content:
  sources: # Keep in alphabetical order by URL
    - url: . # common module containing just the main index
      branches: HEAD
    - url: https://github.com/quarkiverse/quarkus-amazon-alexa
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-amazon-services
      branches: [HEAD, '{1..9}*({0..9})?(.+({0..9})).x']
      version:
        main: dev # fallback to using the matched refname as the value for other branches
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-angus-mail
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-antivirus
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-antora.git
      branches: [HEAD]
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-apistax
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-arangodb-client
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-argocd
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-artemis
      branches: [HEAD, 3.7.x, 3.5.x]
      tags: [2.1.4, 3.0.7, 3.1.6, 3.2.7]
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-asyncapi.git
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-azure-services
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-backstage
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-barcode
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-bucket4j
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-business-score
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-cert-manager
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-config-extensions
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-couchbase
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-cucumber
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-cxf.git
      branches: ['HEAD', '3.20', '3.15', '3.8', '2.2', '1.5']
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-dapr
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-dashbuilder.git
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-discord4j.git
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-docker-client
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-doma.git
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-easy-retrofit
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-embedded-postgresql.git
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-file-vault
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-fluentjdbc
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-freemarker.git
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-fury.git
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-fx.git
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-github-action.git
      branches: [HEAD]
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-github-app.git
      branches: [HEAD]
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-google-cloud-services
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-groovy.git
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-helm
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-hibernate-search-extras
      branches: [HEAD, 1.x, 2.x, 3.x, 4.x]
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-hibernate-types
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-hivemq-client
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-infinispan-embedded
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-ironjacamar
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-itext
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-jackson-jq
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-jaeger
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-jasperreports
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-jdbc-clickhouse
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-jdbc-singlestore
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-jdbc-sqlite
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-jdbc-sqlite4j
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-jdbi
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-jdiameter
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-jef
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-jgit
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-jgrapht
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-jnosql
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-jpastreamer.git
      branches: [HEAD, 1.x]
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-jsch
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-kafka-streams-processor.git
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-kerberos
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-kiota
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-langchain4j
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-logging-json
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-logging-logback.git
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-logging-manager.git
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-logging-sentry.git
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-logging-splunk.git
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-mailpit
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-mcp-server
      branches: [HEAD, 1.0.x]
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-mdns
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-micrometer-registry.git
      branches: [HEAD, 1.x]
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-minio
      branches: [HEAD, 2.9.x]
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-mockk.git
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-mockserver
      branches: [HEAD, 0.x]
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-mongock.git
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-mybatis.git
      branches: [HEAD, 1.x]
      start_path: mybatis/docs
    - url: https://github.com/quarkiverse/quarkus-nagios
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-neo4j
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-ngrok
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-oidc-proxy
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-omnifaces
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-openapi-generator.git
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-openfga-client.git
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-opensearch.git
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-opentelemetry-exporter.git
      branches: [HEAD, 1.x]
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-operator-sdk
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-oras
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-pact.git
      branches: [HEAD, quarkus-2-support]
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-pdfbox.git
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-playwright.git
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-poi.git
      branches: [HEAD, 1.x]
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-pooled-jms
      branches: [HEAD, 2.3.x, 2.1.x, 1.x]
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-presidio.git
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-prettytime
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-primefaces
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-proxy-wasm
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-quinoa
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-qute-server-pages
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-rabbitmq-client.git
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-reactive-messaging-http
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-reactive-messaging-nats-jetstream
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-renarde
      branches: [HEAD, 1.x]
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-roq
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-scala3
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-shardingsphere-jdbc
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-smallrye-opentracing
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-systemd-notify
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-temporal
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-tika
      branches: [HEAD, '{1..9}*({0..9})?(.+({0..9})).x']
      version:
        main: dev # fallback to using the matched refname as the value for other branches
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-unleash.git
      branches: [HEAD, 0.x]
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-vault
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-web-bundler
      branches: [HEAD]
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-wiremock
      branches: [HEAD, 0.x]
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-zanzibar.git
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-zeebe
      branches: [HEAD, 0.x]
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-zookeeper-client
      branches: HEAD
      start_path: docs
ui:
  bundle:
    url: https://github.com/quarkiverse/antora-ui-quarkiverse/releases/latest/download/ui-bundle.zip
    snapshot: true
runtime:
  fetch: true
asciidoc:
  attributes:
    page-pagination: '@'
    kroki-fetch-diagram: true
  extensions:
    - asciidoctor-kroki
