site:
  title: Quarkiverse Documentation
  url: https://quarkiverse.github.io/quarkiverse-docs/
  start_page: quarkiverse-freemarker::index.adoc

content:
  sources:
  - url: https://github.com/quarkiverse/quarkus-freemarker.git
    branches: [master]
    start_path: docs
  - url: https://github.com/quarkiverse/quarkus-github-app.git
    branches: [master]
    start_path: docs
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
  supplemental_files: ./supplemental-ui

runtime:
  fetch: true
