site:
  title: Quarkiverse Documentation
  url: https://quarkiverse.github.io/quarkiverse-docs/
  start_page: index::index.adoc

content:
  sources:
    - url: . # common module containing just the main index
      branches: HEAD
    - url: https://github.com/quarkiverse/quarkus-freemarker.git
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-github-app.git
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-github-action.git
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-rabbitmq-client.git
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-mybatis.git
      branches: HEAD
      start_path: mybatis/docs
    - url: https://github.com/quarkiverse/quarkus-unleash.git
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-mockk.git
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-cxf.git
      branches: [HEAD, v1.x]
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-logging-splunk.git
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-logging-logback.git
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-logging-sentry.git
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-micrometer-registry.git
      branches: [HEAD, 1.x]
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-hivemq-client
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-google-cloud-services
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-cucumber
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-kerberos
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-operator-sdk
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-logging-json
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-tika
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-amazon-alexa
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-neo4j
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-jsch
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-jgit
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-jgrapht
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-artemis
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-amazon-services
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-azure-services
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-hibernate-search-extras
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-config-extensions
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-vault
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-reactive-messaging-http
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-prettytime
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-file-vault
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-hibernate-types
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-renarde
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-helm
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-quinoa
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-jdbc-sqlite
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-dapr
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-jef
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-couchbase
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-pooled-jms
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-jackson-jq
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-apistax
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-jdbc-clickhouse
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-omnifaces
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-cert-manager
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-zookeeper-client
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-minio
      branches: [HEAD, 2.9.x]
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-shardingsphere-jdbc
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-systemd-notify
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-zanzibar.git
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-jpastreamer.git
      branches: HEAD
      start_path: docs
   - url: https://github.com/quarkiverse/quarkus-asyncapi.git
     branches: HEAD
     start_path: docs
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
  supplemental_files: ./supplemental-ui

runtime:
  fetch: true
  
asciidoc:
  attributes:
    kroki-fetch-diagram: true
  extensions:
  - asciidoctor-kroki
