site:
  title: Quarkiverse Documentation
  url: https://quarkiverse.github.io/quarkiverse-docs/
  start_page: index::index.adoc

content:
  sources:
    - url: . # common module containing just the main index
      branches: HEAD
    - url: https://github.com/quarkiverse/quarkus-freemarker.git
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-github-app.git
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-rabbitmq-client.git
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-mybatis.git
      branches: HEAD
      start_path: mybatis/docs
    - url: https://github.com/quarkiverse/quarkus-unleash.git
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-mockk.git
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-cxf.git
      branches: [HEAD, v0.9]
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-logging-splunk.git
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-logging-logback.git
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-logging-sentry.git
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-micrometer-registry.git
      branches: [HEAD, 1.x]
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-hivemq-client
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-google-cloud-services
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-cucumber
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-kerberos
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-operator-sdk
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-logging-json
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-tika
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-amazon-alexa
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-neo4j
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-jsch
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-jgit
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-artemis
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-amazon-services
      branches: HEAD
      start_path: docs
    - url: https://github.com/quarkiverse/quarkus-hibernate-search-extras
      branches: HEAD
      start_path: docs
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
  supplemental_files: ./supplemental-ui

runtime:
  fetch: true
